#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate aggregated feature-importance bar plots.

This script traverses a directory tree containing model training outputs and
generates mean feature-importance bar plots for valence and arousal models.
Both gain- and split-based importances are supported.

The script preserves the original directory structure assumptions:
- Top-level folders: valence/ and arousal/ (as generated by sample_models.py)
- Nested model directories containing feature importance CSV files

Output:
    - JPEG bar plots and corresponding CSV files written to the output directory.

CLI Arguments:
    --input-dir (str, required):
        Root directory containing model training logs
        split into valence/ and arousal/ subfolders.

    --output-dir (str, optional, default="./plots/importances"):
        Output directory for generated plots and CSV summaries.

    --topN (int, optional, default=20):
        Number of top-ranked features to include in each plot.

    --xmax (float, optional, default=0.05):
        Maximum x-axis value for all plots.

    --axis-label-size (int, optional, default=20):
        Font size for axis labels.

    --tick-label-size (int, optional, default=18):
        Font size for tick labels and feature names.
"""


# =============================================================================
# Imports
# =============================================================================


from __future__ import annotations

import argparse
from pathlib import Path
from typing import List, Optional

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


# =============================================================================
# Default Args
# =============================================================================


DEFAULT_OUTPUT_DIR = "./plots/importances"
DEFAULT_TOP_N = 20
DEFAULT_XMAX = 0.05
DEFAULT_AXIS_LABEL_SIZE = 20
DEFAULT_TICK_LABEL_SIZE = 18


# =============================================================================
# I/O Helpers
# =============================================================================


def read_csv_any(fp: Path) -> Optional[pd.DataFrame]:
    """
    Read a CSV file with flexible delimiter handling and normalized headers.

    Args:
        fp (Path): Path to the CSV file.

    Returns:
        Optional[pd.DataFrame]: Parsed DataFrame or None if loading fails.
    """
    if not fp.exists():
        return None

    for sep in [",", ";", "\t"]:
        try:
            df = pd.read_csv(fp, sep=sep)

            rename = {}
            if "Feature" in df.columns and "feature" not in df.columns:
                rename["Feature"] = "feature"
            if "Importance" in df.columns and "importance" not in df.columns:
                rename["Importance"] = "importance"

            if rename:
                df = df.rename(columns=rename)

            if {"feature", "importance"}.issubset(df.columns):
                return df

        except Exception:
            continue

    return None


# =============================================================================
# Discovery / Traversal
# =============================================================================


def iter_candidate_model_dirs(root: Path) -> List[Path]:
    """
    Identify model directories containing feature importance CSV files.

    Args:
        root (Path): Root directory to search.

    Returns:
        List[Path]: List of unique model directories.
    """
    candidates: List[Path] = []

    for p in root.rglob("*"):
        if not p.is_dir():
            continue

        if any(
            (p / fname).exists()
            for fname in [
                "feature_importance_valence_gain.csv",
                "feature_importance_valence_split.csv",
                "feature_importance_arousal_gain.csv",
                "feature_importance_arousal_split.csv",
                "feature_top20_valence_gain.csv",
                "feature_top20_valence_split.csv",
                "feature_top20_arousal_gain.csv",
                "feature_top20_arousal_split.csv",
            ]
        ):
            candidates.append(p)

    seen = set()
    unique_dirs: List[Path] = []
    for d in candidates:
        key = d.as_posix()
        if key not in seen:
            seen.add(key)
            unique_dirs.append(d)

    return unique_dirs


# =============================================================================
# Plotting
# =============================================================================


def plot_mean_bar(
    df: pd.DataFrame,
    out_jpg: Path,
    out_csv: Path,
    topN: int,
    xmax: Optional[float],
    axis_label_size: int,
    tick_label_size: int,
    title: str,
) -> None:
    """
    Generate and save a mean feature-importance bar plot.

    Args:
        df (pd.DataFrame): Aggregated importance DataFrame.
        out_jpg (Path): Output JPEG path.
        out_csv (Path): Output CSV path.
        topN (int): Number of top features to plot.
        xmax (Optional[float]): Maximum x-axis value.
        axis_label_size (int): Axis label font size.
        tick_label_size (int): Tick label font size.
        title (str): Plot title.
    """
    df_top = df.head(topN)
    df_top.to_csv(out_csv, index=False)

    features = df_top["feature"].tolist()
    values = df_top["mean_rel_importance"].to_numpy()
    y = np.arange(len(features))

    fig, ax = plt.subplots(figsize=(10, 0.45 * len(features) + 2))
    ax.barh(y, values, color="C0")

    ax.set_yticks(y)
    ax.set_yticklabels(features, fontsize=tick_label_size)
    ax.set_xlabel("Mean relative importance", fontsize=axis_label_size)
    ax.set_ylabel("Feature", fontsize=axis_label_size)
    ax.tick_params(axis="x", labelsize=tick_label_size)
    ax.set_title(title, fontsize=axis_label_size)

    ax.invert_yaxis()

    if xmax is not None:
        ax.set_xlim(0.0, xmax)

    plt.tight_layout()
    fig.savefig(out_jpg, dpi=300, format="jpg")
    plt.close(fig)


# =============================================================================
# Selection / Ranking Logic
# =============================================================================


def aggregate_mean_importances(
    records: List[pd.DataFrame],
) -> Optional[pd.DataFrame]:
    """
    Aggregate mean relative feature importances across models.

    Args:
        records (List[pd.DataFrame]): List of per-model importance DataFrames.

    Returns:
        Optional[pd.DataFrame]: Aggregated DataFrame or None if empty.
    """
    if not records:
        return None

    merged = pd.concat(records, axis=0, ignore_index=True)
    return (
        merged.groupby("feature")["rel_importance"]
        .mean()
        .reset_index()
        .rename(columns={"rel_importance": "mean_rel_importance"})
        .sort_values("mean_rel_importance", ascending=False)
    )


# =============================================================================
# Core Logic
# =============================================================================


def build_importance_plots(
    input_dir: Path,
    output_dir: Path,
    topN: int,
    xmax: Optional[float],
    axis_label_size: int,
    tick_label_size: int,
) -> None:
    """
    Core logic for generating aggregated mean feature-importance bar plots across multiple models.

    Args:
        input_dir (Path): Root directory containing model training outputs,
            structured into target-specific subdirectories.
        output_dir (Path): Directory where plots and CSV summaries are written.
            The directory is created if it does not exist.
        topN (int): Number of top-ranked features to include in each plot and CSV.
        xmax (Optional[float]): Optional maximum x-axis value for all plots.
            If None, the axis is scaled automatically.
        axis_label_size (int): Font size for axis labels.
        tick_label_size (int): Font size for tick labels and feature names.

    Returns:
        None
    """
    input_dir = Path(input_dir)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    combinations = [
        ("arousal", "gain"),
        ("arousal", "split"),
        ("valence", "gain"),
        ("valence", "split"),
    ]

    for target, importance_type in combinations:
        root = input_dir / target.capitalize()
        if not root.exists():
            print(f"[WARN] Target folder missing: {root}")
            continue

        model_dirs = iter_candidate_model_dirs(root)
        records: List[pd.DataFrame] = []

        for model_dir in model_dirs:
            fp_main = model_dir / f"feature_importance_{target}_{importance_type}.csv"
            fp_alt = model_dir / f"feature_top20_{target}_{importance_type}.csv"

            df_main = read_csv_any(fp_main)
            df_alt = read_csv_any(fp_alt)

            if df_main is not None:
                df = df_main
            elif df_alt is not None:
                df = df_alt
            else:
                continue

            importance = df["importance"].astype(float).clip(lower=0.0)
            total = float(importance.sum())

            if total > 0.0:
                rel_importance = importance / total
            else:
                rel_importance = importance

            records.append(
                pd.DataFrame(
                    {
                        "feature": df["feature"],
                        "rel_importance": rel_importance,
                    }
                )
            )

        if not records:
            print(f"[INFO] No data for {target} ({importance_type})")
            continue

        aggregated = aggregate_mean_importances(records)
        if aggregated is None:
            continue

        out_jpg = output_dir / f"bar_mean_importance_{target}_{importance_type}.jpg"
        out_csv = output_dir / f"bar_mean_importance_{target}_{importance_type}.csv"
        title = f"{target.capitalize()} {importance_type.capitalize()}"

        plot_mean_bar(
            df=aggregated,
            out_jpg=out_jpg,
            out_csv=out_csv,
            topN=topN,
            xmax=xmax,
            axis_label_size=axis_label_size,
            tick_label_size=tick_label_size,
            title=title,
        )

        print(f"[OK] Saved: {out_jpg}")
        print(f"[OK] Saved: {out_csv}")


# =============================================================================
# CLI
# =============================================================================


def parse_args() -> argparse.Namespace:
    """
    Parse command line arguments.

    Returns:
        argparse.Namespace: Parsed arguments.
    """
    parser = argparse.ArgumentParser(
        description="Generate aggregated feature-importance bar plots."
    )

    parser.add_argument(
        "--input-dir", 
        type=str,
        required=True,
        help="Root directory containing model training logs split into valence/ and arousal/ subfolders."
    )

    parser.add_argument(
        "--output-dir",
        type=str, 
        default=DEFAULT_OUTPUT_DIR,
        help="Output directory for generated plots and CSV summaries."
    )

    parser.add_argument(
        "--topN",
        type=int,
        default=DEFAULT_TOP_N,
        help="Number of top-ranked features to include in each plot."
    )

    parser.add_argument(
        "--xmax",
        type=float,
        default=DEFAULT_XMAX,
        help="Maximum x-axis value for all plots."
    )

    parser.add_argument(
        "--axis-label-size",
        type=int,
        default=DEFAULT_AXIS_LABEL_SIZE,
        help="Font size for axis labels."
    )

    parser.add_argument(
        "--tick-label-size",
        type=int,
        default=DEFAULT_TICK_LABEL_SIZE,
        help="Font size for tick labels and feature names."
    )

    args = parser.parse_args()
    return args


# =============================================================================
# Entry Point
# =============================================================================


def main() -> None:
    """
    CLI entry point.
    """
    args = parse_args()
    build_importance_plots(
        input_dir=Path(args.input_dir),
        output_dir=Path(args.output_dir),
        topN=args.topN,
        xmax=args.xmax,
        axis_label_size=args.axis_label_size,
        tick_label_size=args.tick_label_size,
    )


if __name__ == "__main__":
    main()